/**
 * Main screen components are exported from here.
 * To import aditional symbols from a specific screen
 * import that module directly;
 */

export { default as FavoritesList } from './FavoritesList'
export { default as MainList } from './MainList'
export { default as TopGainersList } from './TopGainersList'

//This file is manually maintained at the moment but could be generated by a script
